services:
  db:
    image: postgres:16
    ports:
      - "54322:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chosei
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
